# Generated by Django 3.1.2 on 2020-11-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymain',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, null=True, to='activity.DaysOfTheWeek'),
        ),
    ]
