# Generated by Django 3.1.2 on 2020-11-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_auto_20201110_0228"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitymain",
            name="days_of_week",
        ),
    ]
