# Generated by Django 3.1.2 on 2020-11-19 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0005_auto_20201119_0623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitymain",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="activitymain",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
