# Generated by Django 3.1.2 on 2020-11-06 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Mass')], default=0)),
                ('slug', models.CharField(editable=False, max_length=255)),
                ('is_recurring', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('duration_days', models.PositiveSmallIntegerField(default=1)),
                ('days_of_week', models.ManyToManyField(to='activity.DaysOfTheWeek')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitymain')),
            ],
        ),
    ]
