# Generated by Django 3.1.2 on 2020-10-21 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='familycard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of expiry'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of issue'),
        ),
    ]
