# Generated by Django 3.1.2 on 2021-05-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210524_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycard',
            name='card_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='card number'),
        ),
    ]
