# Generated by Django 3.1.2 on 2020-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name of the authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title of the book'),
        ),
        migrations.AlterField(
            model_name='bookcollection',
            name='description',
            field=models.CharField(max_length=128, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bookcollection',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Name of the collection'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title of section'),
        ),
    ]
