# Generated by Django 3.1.2 on 2020-11-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_auto_20201106_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='image',
        ),
    ]
