# Generated by Django 3.2.4 on 2021-06-25 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reading', '0002_auto_20210524_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reading',
            new_name='Blog',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='section',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookCollection',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Verse',
        ),
    ]
