# Generated by Django 3.1.2 on 2020-10-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_auto_20201021_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reading.bookcollection'),
            preserve_default=False,
        ),
    ]
