# Generated by Django 3.1.2 on 2020-11-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0003_remove_reading_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
